name: Creative Reba
favicon: null
layout_spectrum: 0.82842
typography_spectrum: 0.71753
title: Rebecca Batdorf's Art Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#7977a4'
    - '#442246'
    - '#babeee'
    - '#f5f5f5'
  brandStrength: 0.375
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
