name: Creative Reba
favicon: null
layout_spectrum: 0.82409
typography_spectrum: 0.11579
title: Rebecca Batdorf Art Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#acb6f0'
    - '#000000'
    - '#fefefe'
    - '#323232'
    - '#e26480'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
