name: Creative Reba
favicon: null
layout_spectrum: 0.9799376586452127
typography_spectrum: 0.42060961318202317
title: Rebecca Batdorf Art Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8412237726151943
  lightness: 0.2589624391403049
  saturation: 0.22450621891766787
  rhythmicContrast: 0.8524720543064177
purpose: []
